spring.application.name=mobileProject
spring.datasource.url= jdbc:postgresql://localhost:5433/mobileProject
spring.datasource.username=postgres
spring.datasource.password=nityam

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.cache.type = simple
#spring.cache.type = redis
#spring.redis.host = localhost
#spring.redis.port = 6379

management.endpoints.web.exposure.include= *
 